project:
  type: website
  output-dir: docs 

website:  
  title: "Welcome"
  description: "Oliver is aiming to become a computational neuroscientist"
  bread-crumbs: false
  
  repo-url: https://github.com/OliverMount/OliverMount.github.io
  repo-actions: [edit, source, issue] 
  
  #-----------------------------------------------------------------------------
  ## Top navigation bar
  #-----------------------------------------------------------------------------
  
  
  navbar: 
    left:
      - href: index.qmd
        text: "Home"
      - href: about.qmd
        text: "About"
    right:  
      - href: Simulations/Neuron/Fundamentals.qmd 
        text: "Neuron" 
        
    #--------------------------------------------------------------------------- 
    # Sidebar
    #--------------------------------------------------------------------------- 
    
    sidebar:    
      - title: "About"
        style: "docked"  # or "floated" 
        search: true
        background: light
        foreground: dark
        contents:
          - about.qmd
      
      - title: "Neuron"
        contents:
          - Simulations/Neuron/Fundamentals.qmd 
     
  page-footer: 
    right: "Copyright Feb. 2025, Oliver"
    left: 
      - icon: github
        href: https://github.com/OliverMount

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc_depth: 3
    toc_float: true
    toc_smooth_scroll: true
    toc_highlight: true
    fig-align: center
    

editor: visual

