project:
  type: website
  output-dir: docs 

website:  
  title: "Welcome"
  description: "Oliver is aiming to become a computational neuroscientist"
  
  page-navigation: true
  search: true
  
  repo-url: https://github.com/OliverMount/OliverMount.github.io
  repo-actions: [edit, source, issue] 
  
  #-----------------------------------------------------------------------------
  ## Top navigation bar
  #-----------------------------------------------------------------------------  
  navbar: 
    background: primary
    left:
      - text: "Home"
        href: index.qmd 
      - text: "Research"
        href: Research/Research.qmd 
      - text: "Publications"
        href: Publications/Publications.qmd
      - text: "Tutorials"
        href: Tutorials/Tutorials.qmd
    right:
      - text: "R"
        href: Simulations/R/R.qmd 
      - text: "Python"
        href: Simulations/Python/Python.qmd 
      - text: "Brian2" 
        href: Simulations/Brian2/Brian2.qmd 
      - text: "Neuron" 
        href: Simulations/Neuron/Neuron.qmd  
        
    #--------------------------------------------------------------------------- 
    # Sidebar
    #--------------------------------------------------------------------------- 
    
  sidebar:    
    
    # For left-side items
    - title: "Research"
      style: "docked"  # or "floated" 
      search: true
      background: light 
      contents:
        - Research/Research.qmd 
          
    - title: "Publications"   
      contents:
        - Publications/Publications.qmd
          
    - title: "Tutorials"   
      contents:
        - Tutorials/Tutorials.qmd 
          
    # For right-side  items   
      
    - title: "R"
      contents:
        - Simulations/R/R.qmd  
          
    - title: "Python"
      contents:
        - Simulations/Python/Python.qmd   
      
 
    - title: "Neuron"
      contents:
        - section: "Neuron"
          contents:
            - Simulations/Neuron/Neuron.qmd 
            - Simulations/Neuron/Introduction.qmd 
            - Simulations/Neuron/Fundamentals.qmd 
          
    - title: "Brian2"
      contents:
        - Simulations/Brian2/Brian2.qmd 
        - Simulations/Brian2/Introduction.qmd 
        - Simulations/Brian2/Fundamentals.qmd
     
  page-footer: 
    right: "Copyright Feb. 2025, Oliver" 
    left: 
      - icon: github
        href: https://github.com/OliverMount
        

format:
  html:
    theme: 
      - cosmo
      - brand 
    css: styles.css
    toc: true 

editor: visual

