project:
  type: website
  output-dir: docs
  
  render: 
    - index.qmd
    - about.qmd

website: 
  title: "Welcome"
  description: "Oliver is aiming to become a computational neuroscientist"
  
  sidebar: 
    style: "docked"
    search: true
    contents: 
      - text : "Research"
      - section: "Basics"
      
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About 
    right: 
      - text: "More"
        menu: 
          - text: "Talks"
          - text: "Miscel"
      - text: "R"
        menu: 
          - text: "SPCC package"
            href: https://github.com/OliverMount/varSPCC.git
          - text: "Spike package"
      - text: "Python"
        menu: 
          - text: "dycompy package" 
  page-footer: 
    right: "Copyright Feb. 2025, Oliver"
    left: 
      - icon: github
        href: https://github.com/OliverMount

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc_depth: 3
    toc_float: true
    toc_smooth_scroll: true
    toc_highlight: true
    fig-align: center
    

editor: visual

