---
title: "List of publications" 
bibliography: references.bib 
---

## bioR$\color{Maroon}{\chi}$*iv*

**James, Oliver** and Kim, Y. J. (2025), "Gain-controlled reconfiguration of long-range coupling explains visibility-dependent spatiotemporal neural coding dynamics'', Submitted, Sep. 2025 [https://www.biorxiv.org/content/10.1101/2025.09.24.677967v1](#0)

Jea Kwon, Sunpil Kim, Junsung Woo, Keiko Tanaka-Yamamoto, **James, Oliver**, Erik De Schutter, Sungho Hong, and C. Justin Lee, (2025), "Cerebellar tonic inhibition orchestrates the maturation of information processing and motor coordination'', **Revised to Experimental and Molecular Medicine, Sep. 2025** [https://www.biorxiv.org/content/10.1101/2024.05.30.596563v1](#0) .

## arXiv

**James, Oliver.**, & Lee, H.-N. (2025). "Concise probability distributions of eigenvalues of real-valued Wishart matrices", Retrieved from <http://arxiv.org/abs/1402.6757>

**James, Oliver.**, & Lee, H.-N. (2025). "Restricted isometry random variables: probability distributions, RIC prediction and phase transition analysis for Gaussian encoders", Retrieved from <https://arxiv.org/abs/1410.1956>

## Under Revision

Lee, Y. B., \textbf{James, Oliver}, Lee, D. Y., and Kim, Y. J. (2025). "Hierarchical summary statistics encoding across primary visual and posterior parietal cortices'', **Adanced Science.**

## In Preparation

Miguel Sanchez-Valpuesta, **James, Oliver**, Joonyeol Lee and Gunsoo Kim, "Effects of locomotion on the population frequency representation in the mouse auditory midbrain'', **Writing stage**.

**Oliver James** and Sung Ho Hong, (2025). "Container-based framework for simulating biological cerebellar neural networks", **Writing stage**.

## Journals {#sec-journals}

Bae, J., Jung, K., **James, Oliver.**, Suzuki, S., & Kim, Y. J. (2025). "Frontal engagement in perceptual integration under low subjective visibility", ***NeuroImage***, *305*, 120984.

Do, J., **James, Oliver**., & Kim, Y.-J. (2024). "Choice-dependent delta-band neural trajectory during semantic category decision making in the human brain", **Iscience,** 27(7).

Do, J., Eo, K. Y., **James, Oliver**., Lee, J., & Kim, Y.-J. (2022). "The representational dynamics of sequential perceptual averaging", **Journal of Neuroscience**, 42(6), 1141–1153.

Adalarasu, K., Jagannath, M., & **James, Oliver.** (2020). "Assessment of techniques for teaching school children with autism", **IRBM**, 41(2), 88–93.

**James, Oliver**., Park, H., & Kim, S.-G. (2019). "Impact of sampling rate on statistical significance for single subject fMRI connectivity analysis", **Human Brain Mapping**, 40(11), 3321–3337.

Park, B.-Y., Shim, W. M., **James, Oliver.**, & Park, H. (2019). "Possible links between the lag structure in visual cortex and visual streams using fMRI", **Scientific Reports**, 9(1), 4283.

Eo, K., **James, Oliver**., Son, S., Kang, M.-S., Chong, S. C., & Kim, Y.-J. (2018). "Representational dynamics of ensemble average of simultaneously presented objects", **Journal of Vision**, 18(10), 80–80.

Kwon, J., Kim, M., Park, H., Kang, B.-M., Jo, Y., Kim, J.-H., **Oliver James**… Others. (2017). "Label-free nanoscale optical metrology on myelinated axons in vivo", **Nature Communications**, 8(1), 1832.

Lee, Y., Park, B.-Y., **James, Oliver.**, Kim, S.-G., & Park, H. (2017). "Autism spectrum disorder related functional connectivity changes in the language network in children, adolescents and adults", **Frontiers in Human Neuroscience**, 11, 418.

**James, Oliver**. (2016). "Revisiting the RIP of Real and Complex Gaussian Sensing Matrices Through RIV Framework", **Wireless Personal Communications**, 87(10), 513–526.

**James, Oliver**. (2015). "Stability Analysis of LASSO and Dantzig Selector via Constrained Minimal Singular Value of Gaussian Sensing Matrices", **International Journal of Computer Applications**, 975, 8887.

**James, Oliver**, Lee, W.-B., Park, S.-J., & Lee, H.-N. (2013b). "Evaluation of Resolution Improvement Ability of a DSP Technique for Filter-Array-Based Spectrometers", **The Journal of Korean Institute of Communications and Information Sciences**, 38(6), 497–502.

**James, Oliver**, WoongBi, L., Heung-No, & Lee. (2013). "Filters with random transmittance for improving resolution in filter-array-based spectrometers", **Optics Express**, 21(4), 3969–3989.

**James, Oliver**., Lee, W., Park, S., & Lee, H.-N. (2012). Improving resolution of miniature spectrometers by exploiting sparse nature of signals. **Optics Express**, 20(3), 2613–2625.

**Oliver, James**, Aravind, R., & Prabhu, K. M. M. (2012). Improved least squares channel estimation for orthogonal frequency division multiplexing. **IET Signal Processing**, 6(1), 45–53.

**James, Oliver**, Aravind, R., & Prabhu, K. M. M. (2010). A Krylov subspace based low-rank channel estimation in OFDM systems. **Signal Processing**, 90(6), 1861–1872.

**James, Oliver**., Aravind, R., & Prabhu, K. M. M. (2008). Sparse channel estimation in OFDM systems by threshold-based pruning. **Electronics Letters**, 44(13), 830–832.

## Book Chapters

Umapathy, K., Muthukumaran, D., Chandramohan, S., Sivakumar, M., **James, O.** (2023). Low Power Methodologies for FPGA—An Overview. In: Sharma, D.K., Sharma, R., Jeon, G., Polkowski, Z. (eds) **Low Power Architectures for IoT Applications. Springer Tracts in Electrical and Electronics Engineering.** Springer, Singapore. https://doi.org/10.1007/978-981-99-0639-0_4

## Conferences

**James**, **Oliver** and Yee Joon Kim, (2023) On the representation of objective and subjective visible/invisible stimuli in humans via EEG-based report and no- report, Cognitive Neuroscience Symposium, CNS, SFA, USA

Jisub Bae, **James** **Oliver,** and Yee Joon Kim, (2023) The influence of subjective visibility on illusory contour perception: An EEG study, Cognitive Neuroscience Symposium, CNS, SFA, USA

**James, Oliver.**, Lee, W.-B., & Lee, H.-N. (2013). Random Transmittance Based Filter Array Spectrometers: Sparse Spectrum Recovery And Resolution Improvement. Global Conference on Signal and Information Processing (GlobalSIP), 2013 IEEE, 615–615. IEEE.

**James,Oliver** ., Lee, W.-B., Park, S., & Lee, H.-N. (2013a). A new signal processing technique for improving resolution of spectrometers. 한국통신학회 학술대회논문집, 62–63.

Lee, W.-B., **James,Oliver**, Kim, S.-C., & Lee, H.-N. (2013). Random optical scatter filters for spectrometers: Implementation and Estimation. Imaging Systems and Applications, JTu4A-33. Optica Publishing Group.

**James, Oliver**, S. P., WoongBi Lee, & Lee, H.-N. (2013). Evaluation of resolution improvement capability of a DSP technique for filter-array-based spectrometers. Korean Information and Communication Society Journal, (6), 497–502.

**James, Oliver**, & Lee, H.-N. (2011). A realistic distributed compressive sensing framework for multiple wireless sensor networks. Proc. 4th Signal Process. with Adapt. Sparse Struct. Repr, 105.

**James, Oliver**., Aravind, R., & Prabhu, K. M. M. (2010). Pilot sequence design for improving OFDM channel estimation in the presence of CFO. 2010 International Conference on Signal Processing and Communications (SPCOM), 1–5. IEEE.

**James, Oliver**., Aravind, R., & Prabhu, K. M. M. (2009). Improved channel estimation in OFDM systems in the presence of CFO. 2009 15th Asia-Pacific Conference on Communications, 398–401. IEEE.

**James, Oliver**, Kumari, R. S. S., & Sadasivam, V. (2005). Wavelets for improving spectral efficiency in a digital communication system. Sixth International Conference on Computational Intelligence and Multimedia Applications (ICCIMA’05), 198–203. IEEE.

## International Patents

Heung-No Lee, **Oliver James**, Sang-Jun Park, and Woong-Bi Lee, Method and Apparatus for Processing Optical Signal Of Spectrometer Using Sparse Nature of Signals, US patent number: 13/711,930, date: Dec. 12, 2012. (Contribution 30%).

## Korean Patents

Heung-No Lee, **Oliver James**, and Woong-Bi Lee, Apparatus for Improving Spectral resolution using Random Transmittance in Optical Spectrometers, No. 10-2012-0112453, registered date: Oct. 10, 2012. (Contribution 30%).

Heung-No Lee, **Oliver James**, Sang-Jun Park, and Woong-Bi Lee, Method and Apparatus for Processing Optical Signal Of Spectrometer Using Sparse Nature of Signals, No. 10-2012-0079171, registered date: July. 20, 2012. (Contribution 30%).
