# Filtering of random process

The linear time-invariant filters are widely employed in applications ranging from modern communication system, audio processing and radar systems. The input of such systems would be usually random processes. Thus, it is of importance to study the how the statistics of the random processes change as a result of filtering. Of particular importance is the mean and autocorrelation of the input and output processes.

Consider the input/output of an LTI system with the input process being non-zero mean $\mu_x$ and autocorrelation $r_x(k)$

$$
y(n) = \sum_{k=-\infty}^{\infty} h(l)x(n-l)
$$ {#eq-LTI}

### Mean of the output process

The mean of the output process is

$$
\begin{split}
\mathbb{E}[y_n] & = \sum_{k=-\infty}^{\infty} h(l) \mathbb{E}[x(n-l)] \\
& = \mu \sum_{k=-\infty}^{\infty} h(l)  \\
& = \mu H(e^{j0})
\end{split}
$$

The mean of the output process is the product of the mean of the input process and the frequency response of the filter at $w=0$.

### Autocorrelation of the output 

Multiplying both sides of @eq-LTI with $y_{n-k}$ and taking expectation on both sides leads to

$$
\begin{split}
\mathbb{E}[y(n) y^*(n-k)] & = \sum_{k=-\infty}^{\infty} h(l)\mathbb{E}[ x(n-l) y^*(n-k)] \\
r_y(k) & =a  \\
\end{split}
$$
